# Client maintainer: manuel.grizonnet@cnes.fr
set(CTEST_DASHBOARD_ROOT "/home/otbtesting")
set(CTEST_SITE "pc-christophe.cst.cnes.fr")
set(CTEST_BUILD_CONFIGURATION Release)
set(CTEST_BUILD_NAME "Fedora20-64bits-SuperBuild")
set(CTEST_CMAKE_GENERATOR "Unix Makefiles")
set(CTEST_BUILD_COMMAND "/usr/bin/make -j2 -i -k")
set(CTEST_TEST_ARGS PARALLEL_LEVEL 2)
set(CTEST_TEST_TIMEOUT 1500)

set(CTEST_SOURCE_DIRECTORY  "${CTEST_DASHBOARD_ROOT}/sources/orfeo/trunk/OTB-SuperBuild")
set(CTEST_BINARY_DIRECTORY  "${CTEST_DASHBOARD_ROOT}/build/orfeo/trunk/OTB-SuperBuild")
set(CTEST_INSTALL_DIRECTORY "${CTEST_DASHBOARD_ROOT}/install/orfeo/trunk/OTB-SuperBuild")

set(CTEST_HG_COMMAND          "/usr/bin/hg")
set(CTEST_HG_UPDATE_OPTIONS   "-C")

set(CTEST_NIGHTLY_START_TIME "20:00:00 CEST")
set(CTEST_DROP_METHOD "http")
set(CTEST_DROP_SITE "dash.orfeo-toolbox.org")
set(CTEST_DROP_LOCATION "/submit.php?project=OTB")
set(CTEST_DROP_SITE_CDASH TRUE)

set(CTEST_USE_LAUNCHERS TRUE)

#Use superbuild to compile OTB third parties which was provided inside the source in OTB 4.2
set(OTB_INITIAL_CACHE "
CMAKE_INSTALL_PREFIX:PATH=${CTEST_DASHBOARD_ROOT}/install/orfeo/trunk/OTB-SuperBuild
CMAKE_BUILD_TYPE:STRING=${CTEST_BUILD_CONFIGURATION}
OTB_DATA_ROOT:PATH=${CTEST_DASHBOARD_ROOT}/sources/orfeo/trunk/OTB-Data
CTEST_USE_LAUNCHERS:BOOL=${CTEST_USE_LAUNCHERS}
USE_SYSTEM_TIFF:BOOL=ON
USE_SYSTEM_ZLIB:BOOL=ON
USE_SYSTEM_GEOTIFF:BOOL=ON
USE_SYSTEM_JPEG:BOOL=ON
USE_SYSTEM_GDAL:BOOL=ON
USE_SYSTEM_SQLITE:BOOL=ON
USE_SYSTEM_CURL:BOOL=ON
USE_SYSTEM_PNG:BOOL=ON
USE_SYSTEM_OPENCV:BOOL=ON
USE_SYSTEM_QT4:BOOL=ON
USE_SYSTEM_GEOS:BOOL=ON
USE_SYSTEM_FFTW:BOOL=ON
USE_SYSTEM_PROJ:BOOL=ON
USE_SYSTEM_EXPAT:BOOL=OFF
USE_SYSTEM_ITK:BOOL=OFF
USE_SYSTEM_LIBKML:BOOL=OFF
USE_SYSTEM_TINYXML:BOOL=OFF
USE_SYSTEM_MUPARSER:BOOL=OFF
USE_SYSTEM_MUPARSERX:BOOL=OFF
USE_SYSTEM_BOOST:BOOL=OFF
USE_SYSTEM_OSSIM:BOOL=OFF
USE_SYSTEM_OPENTHREADS:BOOL=OFF
USE_SYSTEM_OPENJPEG:BOOL=OFF
")

execute_process(COMMAND ${CMAKE_COMMAND} -E remove_directory ${CTEST_INSTALL_DIRECTORY})
execute_process(COMMAND ${CMAKE_COMMAND} -E make_directory ${CTEST_INSTALL_DIRECTORY})
execute_process(COMMAND ${CMAKE_COMMAND} -E make_directory ${CTEST_INSTALL_DIRECTORY}/lib)
execute_process(COMMAND ${CMAKE_COMMAND} -E make_directory ${CTEST_INSTALL_DIRECTORY}/bin)
execute_process(COMMAND ${CMAKE_COMMAND} -E make_directory ${CTEST_INSTALL_DIRECTORY}/include)

ctest_empty_binary_directory (${CTEST_BINARY_DIRECTORY})

ctest_start(Experimental)
ctest_update(SOURCE "${CTEST_SOURCE_DIRECTORY}")
file(WRITE "${CTEST_BINARY_DIRECTORY}/CMakeCache.txt" ${OTB_INITIAL_CACHE})
ctest_configure (BUILD "${CTEST_BINARY_DIRECTORY}")

# copy some source archives already on disk
execute_process(COMMAND ${CMAKE_COMMAND} -E copy_directory
${CTEST_DASHBOARD_ROOT}/sources/archives-superbuild
${CTEST_BINARY_DIRECTORY})

ctest_read_custom_files(${CTEST_BINARY_DIRECTORY})
ctest_build (BUILD "${CTEST_BINARY_DIRECTORY}")

# before testing, set the LD_LIBRARY_PATH
set(ENV{LD_LIBRARY_PATH} ${CTEST_INSTALL_DIRECTORY}/lib)

ctest_test(BUILD "${CTEST_BINARY_DIRECTORY}/OTB/build" ${CTEST_TEST_ARGS})
ctest_submit ()


