#!/bin/bash

# http://stackoverflow.com/questions/59895/can-a-bash-script-tell-what-directory-its-stored-in
SOURCE="${BASH_SOURCE[0]}"
while [ -h "$SOURCE" ]; do # resolve $SOURCE until the file is no longer a symlink
DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
SOURCE="$(readlink "$SOURCE")"
[[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE" # if $SOURCE was a relative symlink, we need to resolve it relative to the path where the symlink file was located
done
DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"



PATCHES_DIR=$DIR/patches

MODULAR_ROOT=~/dev/src/OTB-modular-test
UNPATCHED_SOURCES=~/dev/src/OTB-modular-test/OTB_Modular-beforepatch
PATCHED_SOURCES=~/dev/src/OTB-modular-test/OTB_Modular

cd ~/dev/src/OTB-modular-test && diff -ur OTB_Modular-nopatch OTB_Modular > $PATCHES_DIR/otbmodular.patch
