SET( CMAKE_CXX_COMPILER "/usr/bin/g++-4.1" CACHE STRING "debianRelease" FORCE )
SET( CMAKE_C_COMPILER "/usr/bin/gcc-4.1" CACHE STRING "debianRelease" FORCE )
SET( COVERAGE_COMMAND "/usr/bin/gcov-4.1" CACHE STRING "debianRelease" FORCE )
SET( CMAKE_BUILD_TYPE "Release" CACHE STRING "debianRelease" FORCE )
SET( BUILD_TESTING "ON" CACHE STRING "debianRelease" FORCE )
SET( BUILD_EXAMPLES "ON" CACHE STRING "debianRelease" FORCE )
SET( OTB_USE_CURL "ON" CACHE STRING "debianRelease" FORCE )
SET( USE_FFTWD "ON" CACHE STRING "debianRelease" FORCE )
SET( USE_FFTWF "ON" CACHE STRING "debianRelease" FORCE )
SET( OTB_DATA_ROOT "/home/christop/OTB/trunk/OTB-Data" CACHE STRING "debianRelease" FORCE )
SET( CMAKE_C_FLAGS " -Wall -Wno-uninitialized -Wno-unused-variable" CACHE STRING "debianRelease" FORCE )
SET( CMAKE_CXX_FLAGS " -Wall -Wno-deprecated -Wno-uninitialized -Wno-unused-variable" CACHE STRING "debianRelease" FORCE )
SET( CMAKE_EXE_LINKER " " CACHE STRING "debianRelease" FORCE )
SET( MAKECOMMAND "/usr/bin/make -i -j 4" CACHE STRING "debianRelease" FORCE )
SET( OTB_GL_USE_ACCEL "ON" CACHE STRING "debianRelease" FORCE )
SET( ITK_USE_REVIEW "ON" CACHE STRING "debianRelease" FORCE )
