SET( CMAKE_BUILD_TYPE "Release" CACHE STRING "debianRelease" FORCE )
SET( OTB_DIR "/home/otbtesting/OTB/OTB-Binary-Nightly" CACHE STRING "debianRelease" FORCE )
SET( CableSwig_DIR "/home/christop/opensource/CableSwig-Binary" CACHE STRING "debianRelease" FORCE )
SET( WRAP_LevelSet OFF CACHE BOOL "debianRelease" FORCE )
SET( WRAP_Morphology OFF CACHE BOOL "debianRelease" FORCE )
SET( WRAP_ChangeDetection OFF CACHE BOOL "debianRelease" FORCE )
SET( WRAP_ITK_DIMS "2" CACHE STRING "debianRelease" FORCE )
SET( WRAP_ITK_JAVA ON CACHE BOOL "debianRelease" FORCE )
SET( JAVA_AWT_INCLUDE_PATH "/usr/lib/jvm/java-6-sun-1.6.0.16/include" CACHE STRING "debianRelease" FORCE )
SET( JAVA_AWT_LIBRARY  "/usr/lib/jvm/java-6-sun-1.6.0.16/jre/lib/amd64" CACHE STRING "debianRelease" FORCE )
SET( JAVA_INCLUDE_PATH "/usr/lib/jvm/java-6-sun-1.6.0.16/include" CACHE STRING "debianRelease" FORCE )
SET( JAVA_INCLUDE_PATH2 "/usr/lib/jvm/java-6-sun-1.6.0.16/include/linux" CACHE STRING "debianRelease" FORCE )
SET( JAVA_JVM_LIBRARY "/usr/lib/jvm/java-6-sun-1.6.0.16/jre/lib/amd64/server"  CACHE STRING "debianRelease" FORCE )
SET(WRAP_ITK_PYTHON ON CACHE BOOL "debianRelease" FORCE )

