SET( CMAKE_BUILD_TYPE "Debug" CACHE STRING "debianDebug" FORCE )
SET( BUILD_TESTING "ON" CACHE STRING "debianDebug" FORCE )
SET( BUILD_EXAMPLES "ON" CACHE STRING "debianDebug" FORCE )
SET( OTB_USE_CURL "ON" CACHE STRING "debianDebug" FORCE )
SET( USE_FFTWD "ON" CACHE STRING "debianDebug" FORCE )
SET( USE_FFTWF "ON" CACHE STRING "debianDebug" FORCE )
SET( OTB_DATA_ROOT "/home/christop/OTB/trunk/OTB-Data" CACHE STRING "debianDebug" FORCE )
SET( OTB_DATA_USE_LARGEINPUT "ON" CACHE STRING "debianDebug" FORCE )
SET( OTB_DATA_LARGEINPUT_ROOT "/home/christop/OTB/trunk/OTB-Data/LargeInput" CACHE STRING "debianDebug" FORCE )
SET( CMAKE_C_FLAGS " -Wall -fprofile-arcs -ftest-coverage" CACHE STRING "debianDebug" FORCE )
SET( CMAKE_CXX_FLAGS " -Wall -Wno-deprecated -fprofile-arcs -ftest-coverage" CACHE STRING "debianDebug" FORCE )
SET( CMAKE_EXE_LINKER "-Wno-deprecated -fprofile-arcs -ftest-coverage" CACHE STRING "debianDebug" FORCE )
SET( MAKECOMMAND "/usr/bin/make -i -j 2" CACHE STRING "debianDebug" FORCE )
SET( OTB_GL_USE_ACCEL "ON" CACHE STRING "debianDebug" FORCE )
SET( ITK_USE_REVIEW "ON" CACHE STRING "debianDebug" FORCE )
