SET( CMAKE_CXX_COMPILER "/usr/bin/g++-4.1" CACHE STRING "debianRelease" FORCE )
SET( CMAKE_C_COMPILER "/usr/bin/gcc-4.1" CACHE STRING "debianRelease" FORCE )
SET( COVERAGE_COMMAND "/usr/bin/gcov-4.1" CACHE STRING "debianRelease" FORCE )
SET( CMAKE_BUILD_TYPE "Release" CACHE STRING "debianRelease" FORCE )
SET( OTB_DIR "/home/otbtesting/OTB/OTB-Binary-Nightly-Gcc4.1" CACHE STRING "debianRelease" FORCE )
SET( WRAP_ITK_DIMS "2" CACHE STRING "debianRelease" FORCE )
