SET(CMAKE_CONFIGURATION_TYPES "RelWithDebInfo" CACHE STRING "" FORCE)
SET(BUILD_TESTING ON CACHE BOOL "" FORCE)

#SET(CMAKE_INSTALL_PREFIX "E:/Validation-OTB/INSTALL" CACHE PATH "" FORCE)
SET(MAKECOMMAND "/usr/bin/make -i -k -j 8" CACHE STRING "" FORCE)
SET(OTB_DATA_ROOT "/ORFEO/otbval/WWW.ORFEO-TOOLBOX.ORG-CS-NIGHTLY/OTB-Data" CACHE STRING "" FORCE)
SET(OTB_DATA_USE_LARGEINPUT ON CACHE BOOL "" FORCE)
SET(OTB_DATA_LARGEINPUT_ROOT "/home2/data/OTB-Data-LargeInput" CACHE PATH "" FORCE)
SET(BUILDNAME "dora" CACHE STRING "" FORCE)
SET(Monteverdi_DIR "/ORFEO/otmane/ORFEO-TOOLBOX/otb-build/Monteverdi" CACHE PATH "" FORCE)

#SET(GDAL_INCLUDE_DIR "E:/Validation-OTB/OTB-OUTILS/gdal/gdal-1.6.0-Win32-vc8-Release/include" CACHE PATH "" FORCE)
SET(CPACK_PACKAGE_NAME "GE-Monteverdi-Nightly" CACHE STRING "" FORCE)
