SET (ENV{DISPLAY} ":0.0")

SET (CTEST_SOURCE_DIRECTORY "$ENV{HOME}/dev/src/OTB")
SET (CTEST_BINARY_DIRECTORY "$ENV{HOME}/dev/build/OTB")

SET( CTEST_CMAKE_GENERATOR  "Unix Makefiles" )
SET (CTEST_CMAKE_COMMAND "cmake" )
SET (CTEST_BUILD_COMMAND "/usr/bin/make -j10 -i -k install" )
SET (CTEST_SITE "hulk.c-s.fr" )
SET (CTEST_BUILD_NAME "Ubuntu10.04-64bits-Release")
SET (CTEST_BUILD_CONFIGURATION "Release")
SET (CTEST_HG_COMMAND "/usr/bin/hg")
SET (CTEST_HG_UPDATE_OPTIONS "-C")

SET(OTB_INSTALL_PREFIX $ENV{HOME}/dev/install/OTB)

SET (OTB_INITIAL_CACHE "
BUILDNAME:STRING=${CTEST_BUILD_NAME}
SITE:STRING=${CTEST_SITE}

OTB_DATA_USE_LARGEINPUT:BOOL=OFF
OTB_DATA_LARGEINPUT_ROOT:STRING=/DATA/OTB-Data-LargeInput
OTB_DATA_ROOT:STRING=$ENV{HOME}/dev/src/OTB-Data

CMAKE_C_FLAGS:STRING= -Wall -Wno-uninitialized -Wno-unused-variable
CMAKE_CXX_FLAGS:STRING= -Wall -Wno-deprecated -Wno-uninitialized -Wno-unused-variable

CMAKE_BUILD_TYPE:STRING=Release
BUILD_TESTING:BOOL=ON
BUILD_EXAMPLES:BOOL=ON

#OTB_USE_CURL:BOOL=ON
#OTB_USE_PQXX:BOOL=OFF
#ITK_USE_PATENTED:BOOL=ON
#OTB_USE_PATENTED:BOOL=ON
#OTB_USE_EXTERNAL_BOOST:BOOL=ON
#OTB_USE_EXTERNAL_EXPAT:BOOL=ON
#USE_FFTWD:BOOL=OFF
#USE_FFTWF:BOOL=OFF
#OTB_GL_USE_ACCEL:BOOL=ON
#ITK_USE_REVIEW:BOOL=ON 
#ITK_USE_OPTIMIZED_REGISTRATION_METHODS:BOOL=ON 

CMAKE_INSTALL_PREFIX:STRING=${OTB_INSTALL_PREFIX}

")

SET( OTB_PULL_RESULT_FILE "${CTEST_BINARY_DIRECTORY}/pull_result.txt" )

SET (CTEST_NOTES_FILES
${CTEST_SCRIPT_DIRECTORY}/${CTEST_SCRIPT_NAME}
${OTB_PULL_RESULT_FILE}
${CTEST_BINARY_DIRECTORY}/CMakeCache.txt
)

execute_process(COMMAND ${CTEST_CMAKE_COMMAND} -E remove_directory ${OTB_INSTALL_PREFIX})
execute_process(COMMAND ${CTEST_CMAKE_COMMAND} -E make_directory ${OTB_INSTALL_PREFIX})
ctest_empty_binary_directory (${CTEST_BINARY_DIRECTORY})

execute_process( COMMAND ${CTEST_HG_COMMAND} pull http://hg.orfeo-toolbox.org/OTB-Nightly
                 WORKING_DIRECTORY "${CTEST_SOURCE_DIRECTORY}"
                 OUTPUT_VARIABLE   OTB_PULL_RESULT
                 ERROR_VARIABLE    OTB_PULL_RESULT )
file(WRITE ${OTB_PULL_RESULT_FILE} ${OTB_PULL_RESULT} )

ctest_start(Nightly)
ctest_update(SOURCE "${CTEST_SOURCE_DIRECTORY}")
file(WRITE "${CTEST_BINARY_DIRECTORY}/CMakeCache.txt" ${OTB_INITIAL_CACHE})
ctest_configure (BUILD "${CTEST_BINARY_DIRECTORY}")
ctest_build (BUILD "${CTEST_BINARY_DIRECTORY}")
ctest_test (BUILD "${CTEST_BINARY_DIRECTORY}" PARALLEL_LEVEL 6)
ctest_submit ()

