SET( CMAKE_BUILD_TYPE "Release" CACHE STRING "openSolaris" FORCE )
SET( BUILD_TESTING ON CACHE BOOL "openSolaris" FORCE )
SET( BUILD_EXAMPLES OFF CACHE BOOL "openSolaris" FORCE )

SET( OTB_DATA_ROOT "/export/home/christop/OTB/trunk/OTB-Data" CACHE STRING "openSolaris" FORCE )

SET( MAKECOMMAND "/usr/gnu/bin/make -i" CACHE STRING "openSolaris" FORCE )
SET( OTB_USE_EXTERNAL_FLTK OFF CACHE BOOL "openSolaris" FORCE )
SET( OTB_USE_LIBLAS OFF CACHE BOOL "openSolaris" FORCE )

