SET (ENV{DISPLAY} ":0.0")

SET (CTEST_SOURCE_DIRECTORY  "$ENV{HOME}/OTB/trunk/OTB-Wrapper/")
SET (CTEST_BINARY_DIRECTORY  "$ENV{HOME}/OTB/bin/OTB-Wrapper-Nightly/")

SET( CTEST_CMAKE_GENERATOR     "Unix Makefiles" )
SET (CTEST_CMAKE_COMMAND       "cmake" )
SET (CTEST_BUILD_COMMAND       "/usr/bin/make -j2 -i -k" )
SET (CTEST_SITE                "pc-christophe.cst.cnes.fr" )
SET (CTEST_BUILD_NAME          "ArchLinux2010.5-64bits-Release")
SET (CTEST_BUILD_CONFIGURATION "Release")
SET (CTEST_HG_COMMAND          "/usr/bin/hg")
SET (CTEST_HG_UPDATE_OPTIONS   "-C")


#SET(OTB_GDAL_INSTALL_DIR "$ENV{HOME}/OTB-OUTILS/gdal/install-linux-gdal-1.7.2")

SET (OTB_INITIAL_CACHE "

BUILDNAME:STRING=${CTEST_BUILD_NAME}
SITE:STRING=${CTEST_SITE}
CTEST_USE_LAUNCHERS:BOOL=ON

CMAKE_BUILD_TYPE:STRING=${CTEST_BUILD_CONFIGURATION}
BUILD_TESTING:BOOL=ON

CMAKE_C_FLAGS:STRING= -fPIC -Wall -Wno-uninitialized -Wno-unused-variable
CMAKE_CXX_FLAGS:STRING= -fPIC -Wall -Wno-deprecated -Wno-uninitialized -Wno-unused-variable

OTB_DATA_ROOT:STRING=$ENV{HOME}/OTB/trunk/OTB-Data
#OTB_DATA_USE_LARGEINPUT:BOOL=ON
#OTB_DATA_LARGEINPUT_ROOT:STRING=/media/otbnas/otb/OTB-LargeInput

OTB_DIR:STRING=$ENV{HOME}/OTB/bin/OTB-Nightly/
#FLTK_DIR:PATH=$ENV{HOME}/OTB-OUTILS/fltk/binaries-linux-shared-release-fltk-1.1.9

#MAPNIK_INCLUDE_DIR:PATH=/ORFEO/otbval/OTB-OUTILS/mapnik/install/include
#MAPNIK_LIBRARY:FILEPATH=/ORFEO/otbval/OTB-OUTILS/mapnik/install/lib/libmapnik.so
#GDAL_INCLUDE_DIR:STRING=${OTB_GDAL_INSTALL_DIR}/include

#SWIG_DIR:PATH=$ENV{HOME}/OTB-OUTILS/swig/install-linux
#SWIG_EXECUTABLE:FILEPATH=$ENV{HOME}/OTB-OUTILS/swig/install-linux/bin/swig

#WRAP_PYQT:BOOL=ON
WRAP_PYTHON:BOOL=ON
WRAP_QT:BOOL=ON

WRAP_CSHARP:BOOL=OFF
WRAP_JAVA:BOOL=OFF
WRAP_LUA:BOOL=OFF
WRAP_R:BOOL=OFF
WRAP_RUBY:BOOL=OFF
WRAP_TCL:BOOL=OFF

")

SET (CTEST_NOTES_FILES
${CTEST_SCRIPT_DIRECTORY}/${CTEST_SCRIPT_NAME}
${CTEST_BINARY_DIRECTORY}/CMakeCache.txt
)

#execute_process(COMMAND ${CTEST_CMAKE_COMMAND} -E remove_directory ${CTEST_INSTALL_DIRECTORY})
#execute_process(COMMAND ${CTEST_CMAKE_COMMAND} -E make_directory ${CTEST_INSTALL_DIRECTORY})
ctest_empty_binary_directory (${CTEST_BINARY_DIRECTORY})
ctest_start(Nightly)
ctest_update(SOURCE "${CTEST_SOURCE_DIRECTORY}")
file(WRITE "${CTEST_BINARY_DIRECTORY}/CMakeCache.txt" ${OTB_INITIAL_CACHE})
ctest_configure (BUILD "${CTEST_BINARY_DIRECTORY}")
ctest_read_custom_files(${CTEST_BINARY_DIRECTORY})
ctest_build (BUILD "${CTEST_BINARY_DIRECTORY}")
ctest_test (BUILD "${CTEST_BINARY_DIRECTORY}" PARALLEL_LEVEL 2)
ctest_submit ()

