SET(BUILDNAME "PC7450-Nightly-TestDriver-Release-Internal-ITK-Internal-FLTK-With-OSGEO" CACHE STRING "" FORCE)
SET(CMAKE_BUILD_TYPE "Release" CACHE STRING "" FORCE)
SET(BUILD_TESTING ON CACHE BOOL "" FORCE)
SET(BUILD_EXAMPLES ON CACHE BOOL "" FORCE)
SET(CMAKE_INSTALL_PREFIX "D:/Developpement/OTB-NIGHTLY-VALIDATION/OSGEO-Release/binaries/install/OTB" CACHE PATH "" FORCE)
SET(MAKECOMMAND "C:\PROGRA~1\MICROS~1.0\Common7\IDE\VCExpress.exe" CACHE STRING "" FORCE)
SET(OTB_DATA_ROOT "D:/Developpement/OTB-hg/OTB-Data" CACHE STRING "" FORCE)
SET(OTB_USE_EXTERNAL_FLTK OFF CACHE BOOL "" FORCE)

SET(GDAL_INCLUDE_DIR "C:/OSGeo4W/apps/gdal-16/include" CACHE PATH "" FORCE)
SET(GDAL_LIBRARY "C:/OSGeo4W/apps/gdal-16/lib/gdal_i.lib" CACHE PATH "" FORCE)

SET(GEOTIFF_INCLUDE_DIRS "C:/OSGeo4W/include" CACHE PATH "" FORCE)
SET(GEOTIFF_LIBRARY "C:/OSGeo4W/lib/geotiff_i.lib" CACHE PATH "" FORCE)

SET(JPEG_INCLUDE_DIRS "C:/OSGeo4W/include" CACHE PATH "" FORCE)
SET(JPEG_INCLUDE_DIR "C:/OSGeo4W/include" CACHE PATH "" FORCE)
SET(JPEG_LIBRARY "C:/OSGeo4W/lib/jpeg_i.lib" CACHE PATH "" FORCE)

SET(TIFF_INCLUDE_DIRS "C:/OSGeo4W/include" CACHE PATH "" FORCE)
SET(TIFF_LIBRARY "C:/OSGeo4W/lib/libtiff_i.lib" CACHE PATH "" FORCE)

SET(OTB_USE_CURL ON CACHE BOOL "" FORCE)
SET(CURL_INCLUDE_DIR "C:/OSGeo4W/include" CACHE PATH "" FORCE)
SET(CURL_LIBRARY "C:/OSGeo4W/lib/libcurl_imp.lib" CACHE PATH "" FORCE)

SET(CPACK_PACKAGE_NAME "OTB-Nightly" CACHE STRING "" FORCE)
