SET( CMAKE_BUILD_TYPE "Release" CACHE STRING "ubuntuRelease" FORCE )
SET( OTB_DIR "/home/otbtesting/OTB/OTB-Binary-Continuous" CACHE STRING "ubuntuRelease" FORCE )
SET( OTB_DATA_ROOT "/mnt/sdb1/OTB/trunk/OTB-Data" CACHE STRING "ubuntuRelease" FORCE )
SET( BUILD_TESTING "ON" CACHE STRING "ubuntuRelease" FORCE )
SET( OTB_USE_VTK "ON" CACHE STRING "ubuntuRelease" FORCE )
SET( CMAKE_C_FLAGS " -Wall  -Wno-uninitialized -Wno-unused-variable" CACHE STRING "ubuntuRelease" FORCE )
SET( CMAKE_CXX_FLAGS " -Wall -Wno-deprecated -Wno-uninitialized -Wno-unused-variable" CACHE STRING "ubuntuRelease" FORCE )
SET( CMAKE_EXE_LINKER " " CACHE STRING "ubuntuRelease" FORCE )
SET( MAKECOMMAND "/usr/bin/make -i -k -j 8 -k" CACHE STRING "ubuntuRelease" FORCE )
