SET( SITE "pc-grizonnetm" CACHE STRING "ubuntuDebug" FORCE )
SET( CMAKE_BUILD_TYPE "Debug" CACHE STRING "ubuntuDebug" FORCE )
SET( OTB_DIR "/home/grizonnetm/workspace/OTB-Debug@OTB-Binary" CACHE STRING "ubuntuDebug" FORCE )
SET( CableSwig_DIR "/usr/lib/CableSwig" CACHE STRING "ubuntuDebug" FORCE )
SET( WRAP_JAVA OFF CACHE BOOL "ubuntuDebug" FORCE )
SET( WRAP_PYTHON ON CACHE BOOL "ubuntuDebug" FORCE )
SET( WRAP_ITK_PYTHON ON CACHE BOOL "ubuntuDebug" FORCE )
SET( WRAP_ITK_JAVA OFF CACHE BOOL "ubuntuDebug" FORCE )
SET( WRAP_LevelSet OFF CACHE BOOL "ubuntuDebug" FORCE )
SET( WRAP_Morphology OFF CACHE BOOL "ubuntuDebug" FORCE )
SET( WRAP_ChangeDetection OFF CACHE BOOL "ubuntuDebug" FORCE )
SET( WRAP_ITK_DIMS "2" CACHE STRING "ubuntuDebug" FORCE )
SET( JAVA_AWT_INCLUDE_PATH "/usr/lib/jvm/java-6-sun/include" CACHE STRING "ubuntuDebug" FORCE )
SET( JAVA_AWT_LIBRARY  "/usr/lib/jvm/java-6-sun/jre/lib/amd64" CACHE STRING "ubuntuDebug" FORCE )
SET( JAVA_INCLUDE_PATH "/usr/lib/jvm/java-6-sun/include" CACHE STRING "ubuntuDebug" FORCE )
SET( JAVA_INCLUDE_PATH2 "/usr/lib/jvm/java-6-sun/include/linux" CACHE STRING "ubuntuDebug" FORCE )
SET( JAVA_JVM_LIBRARY "/usr/lib/jvm/java-6-sun/jre/lib/amd64/server"  CACHE STRING "ubuntuDebug" FORCE )
SET( OTB_DATA_USE_LARGEINPUT ON CACHE BOOL "ubuntuDebug" FORCE )
SET( OTB_DATA_LARGEINPUT_ROOT "/mnt/dd-2/OTB/trunk/LargeInput" CACHE STRING "ubuntuDebug" FORCE )

SET( SWIG_DIR "/home/grizonnetm/Local/swig-1.3.40-binary/share/swig/1.3.40" CACHE STRING "ubuntuRelease" FORCE )
SET( SWIG_EXECUTABLE "/home/grizonnetm/Local/swig-1.3.40-binary/bin/swig" CACHE STRING "ubuntuRelease" FORCE )
SET( SWIG_VERSION "1.3.40" CACHE STRING "ubuntuRelease" FORCE )


