SET( SITE "pc-grizonnetm" CACHE STRING "ubuntuRelease" FORCE )
SET( CMAKE_BUILD_TYPE "Release" CACHE STRING "ubuntuRelease" FORCE )
SET( Monteverdi_DIR "/mnt/dd-2/OTB/Monteverdi-Binary-Nightly" CACHE STRING "ubuntuDebug" FORCE )
SET( OTB_DATA_ROOT "/mnt/dd-2/OTB/trunk/OTB-Data" CACHE STRING "ubuntuRelease" FORCE )
SET( OTB_DATA_USE_LARGEINPUT ON CACHE BOOL "ubuntuRelease" FORCE )
SET( OTB_DATA_LARGEINPUT_ROOT "/mnt/dd-2/OTB/trunk/LargeInput" CACHE STRING "ubuntuRelease" FORCE )
SET( BUILD_TESTING "ON" CACHE STRING "ubuntuRelease" FORCE )
SET( OTB_USE_VTK "ON" CACHE STRING "ubuntuRelease" FORCE )
SET( CMAKE_C_FLAGS " -Wall  -Wno-uninitialized -Wno-unused-variable" CACHE STRING "ubuntuRelease" FORCE )
SET( CMAKE_CXX_FLAGS " -Wall -Wno-deprecated -Wno-uninitialized -Wno-unused-variable" CACHE STRING "ubuntuRelease" FORCE )
SET( CMAKE_EXE_LINKER " " CACHE STRING "ubuntuRelease" FORCE )
SET( MAKECOMMAND "/usr/bin/make -i -k -j 8" CACHE STRING "ubuntuRelease" FORCE )

SET( CMAKE_INSTALL_PREFIX "/mnt/dd-2/OTB/tmp" CACHE STRING "Used for package generation" FORCE )

SET( OTB_USE_CPACK "OFF" CACHE STRING "ubuntuRelease" FORCE )
