SET( SITE "pc-grizonnetm" CACHE STRING "ubuntuDebug" FORCE )
SET( CMAKE_BUILD_TYPE "Debug" CACHE STRING "ubuntuDebug" FORCE )
SET( BUILD_TESTING ON CACHE BOOL "ubuntuDebug" FORCE )
SET( BUILD_EXAMPLES ON CACHE BOOL "ubuntuDebug" FORCE )
SET( OTB_USE_CURL ON CACHE BOOL "ubuntuDebug" FORCE )
SET( OTB_USE_PQXX ON CACHE BOOL "ubuntuDebug" FORCE)
SET( OTB_USE_EXTERNAL_BOOST ON CACHE BOOL "debianRelease" FORCE )
SET( OTB_USE_EXTERNAL_EXPAT ON CACHE BOOL "debianRelease" FORCE )
SET( OTB_USE_EXTERNAL_FLTK ON CACHE BOOL "debianRelease" FORCE )
SET( USE_FFTWD ON CACHE BOOL "ubuntuDebug" FORCE )
SET( USE_FFTWF ON CACHE BOOL "ubuntuDebug" FORCE )
SET( OTB_DATA_ROOT "/mnt/dd-2/OTB/trunk/OTB-Data" CACHE STRING "ubuntuDebug" FORCE )
SET( OTB_DATA_USE_LARGEINPUT ON CACHE BOOL "ubuntuDebug" FORCE )
SET( OTB_DATA_LARGEINPUT_ROOT "/mnt/dd-2/OTB/trunk/LargeInput" CACHE STRING "ubuntuDebug" FORCE )
SET( CMAKE_C_FLAGS " -Wall -fprofile-arcs -ftest-coverage" CACHE STRING "ubuntuDebug" FORCE )
SET( CMAKE_CXX_FLAGS " -Wall -Wno-deprecated -fprofile-arcs -ftest-coverage" CACHE STRING "ubuntuDebug" FORCE )
SET( CMAKE_EXE_LINKER "-Wno-deprecated -fprofile-arcs -ftest-coverage" CACHE STRING "ubuntuDebug" FORCE )
SET( MAKECOMMAND "/usr/bin/make -i -k -j 4" CACHE STRING "ubuntuDebug" FORCE )
SET( OTB_GL_USE_ACCEL ON CACHE BOOL "ubuntuDebug" FORCE )
SET( ITK_USE_REVIEW ON CACHE BOOL "ubuntuDebug" FORCE )
SET( ITK_USE_OPTIMIZED_REGISTRATION_METHODS ON CACHE BOOL "Multithreaded registration" FORCE )

#SET( OTB_USE_MAPNIK ON CACHE BOOL "Using mapnik" FORCE)
#SET( MAPNIK_INCLUDE_DIR "/home/christop/slash/include" CACHE STRING "mapnik include" FORCE)
#SET( MAPNIK_LIBRARY "/home/christop/slash/lib64/libmapnik.so" CACHE STRING "mapnik lib" FORCE)

SET (GDAL_CONFIG "/home/grizonnetm/Local/gdal-1.6.3-build/bin/gdal-config" CACHE STRING "ubuntuDebug" FORCE)
SET (GDAL_INCLUDE_DIR "/home/grizonnetm/Local/gdal-1.6.3-build/include" CACHE STRING "ubuntuDebug" FORCE)
SET (GDAL_LIBRARY "/home/grizonnetm/Local/gdal-1.6.3-build/lib/libgdal.so" CACHE STRING "ubuntuDebug" FORCE)
SET (OGR_INCLUDE_DIRS "/home/grizonnetm/Local/gdal-1.6.3-build/include" CACHE STRING "ubuntuDebug" FORCE)