SET( HAS_SSE2_EXTENSIONS_EXITCODE
     "0"
     CACHE STRING "Result from TRY_RUN" FORCE)
SET( HAS_SSE_EXTENSIONS_EXITCODE
     "0"
     CACHE STRING "Result from TRY_RUN" FORCE)
SET( IS_X86_64_EXITCODE
     "0"
     CACHE STRING "Result from TRY_RUN" FORCE)
