# OTB Application shared libraries
usr/lib/otb/libOTBApplicationsCommon.so
usr/lib/otb/libotbMVCFineRegistration.so
# usr/lib/otb/libotbMVCImageToDBRegistration.so
usr/lib/otb/libotbMVCImageViewerManager.so
usr/lib/otb/libotbMVCLandCoverMap.so
usr/lib/otb/libotbMVCObjectCounting.so
usr/lib/otb/libotbMVCPolarimetricSynthesis.so
usr/lib/otb/libotbMVCRoadExtraction.so
usr/lib/otb/libotbMVCSegmentation.so
usr/lib/otb/libotbMVCStereoscopic.so
usr/lib/otb/libotbMVCUrbanArea.so

# OTB Application executables
usr/bin/otbImageViewerManagerOld
usr/bin/otbActiveLearning
usr/bin/otbRoadExtractionApplication
usr/bin/otbUrbanAreaExtractionApplication
usr/bin/otbPolarimetricSynthesisApplication
usr/bin/otbPolarimetricSynthesisCommandLine
usr/bin/otbStereoscopicApplication
usr/bin/otbSegmentationApplication
usr/bin/otbFineRegistrationApplication
usr/bin/otbImageViewerManager
usr/bin/otbObjectCountingApplication
usr/bin/otbLandCoverMapApplication
usr/bin/otbLandCoverMapGenerateFeatures
usr/bin/otbImageViewer
# usr/bin/otbImageToDBRegistrationApplication
usr/bin/otbKMeansClassification
usr/bin/otbRgbRelabeling
usr/bin/otbSOMClassification
usr/bin/otbSVMClassification
usr/bin/otbUnsignedShortRelabeling
