# Common shared library
usr/lib/otb/libOTBProcessingChain.so

# OTB Application shared libraries
usr/lib/otb/libOTBEstimateFeaturesStatistics.so
usr/lib/otb/libOTBEvaluateHOGObjectDetectorResponse.so
usr/lib/otb/libOTBEvaluateObjectDetectorResponse.so
usr/lib/otb/libOTBHOGObjectDetector.so
usr/lib/otb/libOTBMeanShiftModesDetection.so
usr/lib/otb/libOTBObjectDetector.so
usr/lib/otb/libOTBTrainDeepSVMObjectDetector.so
usr/lib/otb/libOTBTrainHOGObjectDetector.so
usr/lib/otb/libOTBTrainObjectDetector.so
usr/lib/otb/libOTBImageSimulator.so
usr/lib/otb/libOTBLAIAndPROSAILToSensorResponse.so
usr/lib/otb/libOTBLAIFromNDVIImageTransform.so

