# Common shared library
usr/lib/otb/libOTBProcessingChain.so

# OTB Application shared libraries
usr/lib/otb/libOTBBandMath.so
usr/lib/otb/libOTBBundleToPerfectSensor.so
usr/lib/otb/libOTBCompareImages.so
usr/lib/otb/libOTBComputePolylineFeatureFromImage.so
usr/lib/otb/libOTBConcatenateImages.so
usr/lib/otb/libOTBConnectedComponentSegmentation.so
usr/lib/otb/libOTBConvert.so
usr/lib/otb/libOTBDEMConvert.so
usr/lib/otb/libOTBDSFuzzyModelEstimation.so
usr/lib/otb/libOTBEstimateFeaturesStatistics.so
usr/lib/otb/libOTBEstimateImagesStatistics.so
usr/lib/otb/libOTBEvaluateHOGObjectDetectorResponse.so
usr/lib/otb/libOTBEvaluateObjectDetectorResponse.so
usr/lib/otb/libOTBExtractROIApplication.so
usr/lib/otb/libOTBFineRegistration.so
usr/lib/otb/libOTBHOGObjectDetector.so
usr/lib/otb/libOTBImageSVMClassifier.so
usr/lib/otb/libOTBKmzExport.so
usr/lib/otb/libOTBLabeledImageColorMapping.so
usr/lib/otb/libOTBLineSegmentDetection.so
usr/lib/otb/libOTBMaskGenerator.so
usr/lib/otb/libOTBMeanShiftModesDetection.so
usr/lib/otb/libOTBObjectDetector.so
usr/lib/otb/libOTBOpticalCalibration.so
usr/lib/otb/libOTBOrthoRectification.so
usr/lib/otb/libOTBOSMDownloader.so
usr/lib/otb/libOTBQuicklook.so
usr/lib/otb/libOTBReadImageInfo.so
usr/lib/otb/libOTBRigidTransformResample.so
usr/lib/otb/libOTBSplitImage.so
usr/lib/otb/libOTBSuperimpose.so
usr/lib/otb/libOTBTrainDeepSVMObjectDetector.so
usr/lib/otb/libOTBTrainHOGObjectDetector.so
usr/lib/otb/libOTBTrainImagesClassifier.so
usr/lib/otb/libOTBTrainObjectDetector.so
usr/lib/otb/libOTBValidateImagesClassifier.so
usr/lib/otb/libOTBVectorDataDSValidation.so
usr/lib/otb/libOTBVectorDataExtractROIApplication.so
usr/lib/otb/libOTBVectorDataSetField.so
usr/lib/otb/libOTBVectorDataTransformFilterApplication.so


